export type ColorsTypes = {
  black: string;
  purple: string;
  pink: string;
  pinkLighter: string;
  white: string;
  backgrnd: string;
  primaryLighter: string;
  primaryLight: string;
  primary: string;
  primaryDark: string;
  primaryDarker: string;
  secundary: string;
  secundaryDark: string;
  titleInPrimary: string;
  textInPrimary: string;
  textTitle: string;
  textComplement: string;
  textBase: string;
  lineInWhite: string;
  inputBackground: string;
  buttonText: string;
  boxBase: string;
  boxFooter: string;
};
