export type ColorsTypes = {
  black: string;
  purple: string;
  pink: string;
  white: string;
  grey: string;
  Background: string;
  PrimaryLighter: string;
  PrimaryLight: string;
  Primary: string;
  PrimaryDark: string;
  PrimaryDarker: string;
  Secundary: string;
  SecundaryDark: string;
  TitleInPrimary: string;
  TextInPrimary: string;
  TextTitle: string;
  TextComplement: string;
  TextBase: string;
  LineInWhite: string;
  InputBackground: string;
  ButtonText: string;
  BoxBase: string;
  BoxFooter: string;
};
